# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-24 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=140)),
                ('apellidos', models.CharField(max_length=140)),
                ('cedula', models.IntegerField(unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=140)),
                ('creado', models.DateField(auto_now=True)),
                ('foto', models.ImageField(upload_to='perfil/docentes/')),
                ('fchanac', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('nacionalidad', models.CharField(choices=[('V', 'Venezolana'), ('E', 'Extranjera')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaMaestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.Maestro')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.PeriodoEscolar')),
                ('seccion', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='periodo', chained_model_field='periodo', on_delete=django.db.models.deletion.CASCADE, to='notas.PdoGradoSec')),
            ],
        ),
    ]
