# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-28 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='horas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
