# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-28 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=140)),
                ('apellidos', models.CharField(max_length=140)),
                ('nacionalidad', models.CharField(choices=[('V', 'Venezolana'), ('E', 'Extranjera')], max_length=10)),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=140)),
                ('fchanac', models.DateField()),
                ('lugarnac', models.CharField(blank=True, choices=[('AMAZONAS', 'AMAZONAS'), ('ANZOATEGUI', 'ANZOATEGUI'), ('APURE', 'APURE'), ('ARAGUA', 'ARAGUA'), ('BARINAS', 'BARINAS'), ('BOLIVAR', 'BOLIVAR'), ('CARABOBO', 'CARABOBO'), ('COJEDES', 'COJEDES'), ('DELTA AMACURO', 'DELTA AMACURO'), ('DISTRITO CAPITAL', 'DISTRITO CAPITAL'), ('FALCON', 'FALCON'), ('GUARICO', 'GUARICO'), ('LARA', 'LARA'), ('MERIDA', 'MERIDA'), ('MIRANDA', 'MIRANDA'), ('MONAGAS', 'MONAGAS'), ('NUEVA ESPARTA', 'NUEVA ESPARTA'), ('PORTUGUESA', 'PORTUGUESA'), ('SUCRE', 'SUCRE'), ('TACHIRA', 'TACHIRA'), ('TRUJILLO', 'TRUJILLO'), ('VARGAS', 'VARGAS'), ('YARACUY', 'YARACUY'), ('ZULIA', 'ZULIA'), ('OTRO PAIS', 'OTRO PAIS')], max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=140)),
                ('creado', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.CharField(blank=True, max_length=5, null=True)),
                ('canaima', models.BooleanField()),
                ('estatura', models.CharField(blank=True, max_length=5, null=True)),
                ('talla_c', models.CharField(blank=True, choices=[('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('S', 'S'), ('SS', 'SS'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=50, null=True)),
                ('talla_z', models.IntegerField(blank=True, default=0, null=True)),
                ('talla_p', models.IntegerField(blank=True, default=0, null=True)),
                ('foto', models.ImageField(upload_to='perfil/alumnos/')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='RepresenAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=140, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=140, null=True)),
                ('nacionalidad', models.CharField(blank=True, choices=[('V', 'Venezolana'), ('E', 'Extranjera')], max_length=20)),
                ('cedula', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=20)),
                ('nivel_academico', models.CharField(blank=True, choices=[('Primaria', 'Primaria'), ('Bachiller', 'Bachiller'), ('Universitario', 'Universitario'), ('Maestria', 'Maestria'), ('Especialista', 'Especialista'), ('Doctor', 'Doctor'), ('Ninguno', 'Ninguno')], max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Alumno')),
            ],
        ),
    ]
